/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

void initClk(void)
{
	// Enable HSI
	RCC->CR |= RCC_CR_HSION;
	while(!(RCC->CR & RCC_CR_HSIRDY)){};

	// Enable Prefetch Buffer
	FLASH->ACR |= FLASH_ACR_PRFTBE;

	// Flash 2 wait state
	FLASH->ACR &= ~FLASH_ACR_LATENCY;
	FLASH->ACR |= FLASH_ACR_LATENCY_2;

	// HCLK = SYSCLK
	RCC->CFGR |= RCC_CFGR_HPRE_DIV1;

	// PCLK2 = HCLK
	RCC->CFGR |= RCC_CFGR_PPRE2_DIV1;

	// PCLK1 = HCLK
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV2;

	// PLL configuration: PLLCLK = HSI/2 * 16 = 64 MHz
	RCC->CFGR &= ~RCC_CFGR_PLLSRC;
	RCC->CFGR |= RCC_CFGR_PLLMULL16;

	// Enable PLL
	RCC->CR |= RCC_CR_PLLON;

	// Wait till PLL is ready
	while((RCC->CR & RCC_CR_PLLRDY) == 0) {};

	// Select PLL as system clock source
	RCC->CFGR &= ~RCC_CFGR_SW;
	RCC->CFGR |= RCC_CFGR_SW_PLL;

	// Wait till PLL is used as system clock source
	while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL){};
}

void delay(uint32_t delay_value)
{
	for(uint32_t i = 0; i<delay_value; i++);
}

void init_ports(void)
{
	RCC->APB2ENR |= RCC_APB2ENR_IOPBEN | RCC_APB2ENR_IOPCEN;
	GPIOB->CRL |= (GPIO_CRL_MODE0 | GPIO_CRL_MODE1 | GPIO_CRL_MODE2 | GPIO_CRL_MODE3 |
			GPIO_CRL_MODE4 | GPIO_CRL_MODE5 | GPIO_CRL_MODE6 | GPIO_CRL_MODE7);

	GPIOB->CRH |= GPIO_CRH_MODE13 | GPIO_CRH_MODE14;
	GPIOB->CRH &= ~(GPIO_CRH_CNF13 | GPIO_CRH_CNF14);

	GPIOB->CRL &= ~(GPIO_CRL_CNF0 | GPIO_CRL_CNF1 | GPIO_CRL_CNF2 | GPIO_CRL_CNF3 |
			GPIO_CRL_CNF4 | GPIO_CRL_CNF5 | GPIO_CRL_CNF6 | GPIO_CRL_CNF7);
	//GPIOB->CRL |= (0x33333333); 															//(0011) Push-Pull, Output 50MHz
	GPIOC->CRL |= GPIO_CRL_MODE0 | GPIO_CRL_MODE1 | GPIO_CRL_MODE2 | GPIO_CRL_MODE3;	//(0011) Push-Pull, Output 50MHz
	GPIOC->CRL &= ~(GPIO_CRL_CNF0 | GPIO_CRL_CNF1 | GPIO_CRL_CNF2 | GPIO_CRL_CNF3 );		//(0011) Push-Pull, Output 50MHz
}

void init_tim2(void)
{
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	TIM2->CR1 |= TIM_CR1_URS;
	TIM2->PSC = 8000-1;
	TIM2->ARR = 10;
	TIM2->CR1 |= TIM_CR1_CEN;
}

void init_tim3(void)
{
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
	TIM3->CR1 |= TIM_CR1_URS;
	TIM3->DIER |= TIM_DIER_UIE;
	TIM3->PSC = 32000-1;
	TIM3->ARR = 1000;
	TIM3->CR1 |= TIM_CR1_CEN;

	NVIC_EnableIRQ(TIM3_IRQn);
	NVIC_SetPriority(TIM3_IRQn, 1);
}

void init_adc(void)
{
	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN | RCC_APB2ENR_IOPAEN;
	GPIOA->CRL &= ~(GPIO_CRL_CNF0 | GPIO_CRL_MODE0); //PC5
	ADC1->SMPR2 |= ADC_SMPR2_SMP0;
	ADC1->CR2 |= ADC_CR2_EXTSEL | ADC_CR2_EXTTRIG | ADC_CR2_ADON;
	delay(2);
	ADC1->CR2 |= ADC_CR2_CAL;
	while((ADC1->CR2 & ADC_CR2_CAL) != 0);

}

uint16_t adc = 0;
uint8_t value[4] = {0};


void TIM3_IRQHandler()
{
	TIM3->SR &= ~TIM_SR_UIF;
	convert();
}

void indicator(uint8_t num, uint8_t indicator_index)
{
	GPIOC->BSRR = GPIO_BSRR_BR0 | GPIO_BSRR_BR1 | GPIO_BSRR_BR2 | GPIO_BSRR_BR3; //Сброс PC0-PC3
	GPIOB->BSRR = GPIO_BSRR_BR0 | GPIO_BSRR_BR1 | GPIO_BSRR_BR2 | GPIO_BSRR_BR3 |
			GPIO_BSRR_BR4 | GPIO_BSRR_BR5| GPIO_BSRR_BR6 | GPIO_BSRR_BR7 |
			GPIO_BSRR_BR13 | GPIO_BSRR_BR14; //Сброс PB0-PB7
	GPIOB->BSRR = GPIO_BSRR_BS7; //DP


	//0
	if (num == 0)
	{
		GPIOB->BSRR = GPIO_BSRR_BS0 | GPIO_BSRR_BS1 | GPIO_BSRR_BS2 | GPIO_BSRR_BS13 |
				GPIO_BSRR_BS14 | GPIO_BSRR_BS5;	//ABCDEF
	}

	if (num == 1)
	{
		GPIOB->BSRR = GPIO_BSRR_BS1 | GPIO_BSRR_BS2;	//BC
	}

	if (num == 2)
	{
		GPIOB->BSRR = GPIO_BSRR_BS0 | GPIO_BSRR_BS1 | GPIO_BSRR_BS13 | GPIO_BSRR_BS14 |
				GPIO_BSRR_BS6;	//ABDEG
	}

	if (num == 3)
	{
		GPIOB->BSRR = GPIO_BSRR_BS0 | GPIO_BSRR_BS1 | GPIO_BSRR_BS2 | GPIO_BSRR_BS13 |
				GPIO_BSRR_BS6;	//ABCDG
	}

	if (num == 4)
	{
		GPIOB->BSRR = GPIO_BSRR_BS1 | GPIO_BSRR_BS2 | GPIO_BSRR_BS5 | GPIO_BSRR_BS6;	//BCFG
	}

	if (num == 5)
	{
		GPIOB->BSRR = GPIO_BSRR_BS0 | GPIO_BSRR_BS2 | GPIO_BSRR_BS13 | GPIO_BSRR_BS5 |
				GPIO_BSRR_BS6;	//ACDFG
	}

	if (num == 6)
	{
		GPIOB->BSRR = GPIO_BSRR_BS0 | GPIO_BSRR_BS2 | GPIO_BSRR_BS13 |
				GPIO_BSRR_BS14 | GPIO_BSRR_BS5 | GPIO_BSRR_BS6;	//ACDEFG
	}

	if (num == 7)
	{
		GPIOB->BSRR = GPIO_BSRR_BS0 | GPIO_BSRR_BS1 | GPIO_BSRR_BS2;	//ABC
	}

	if (num == 8)
	{
		GPIOB->BSRR = GPIO_BSRR_BS0 | GPIO_BSRR_BS1 | GPIO_BSRR_BS2 | GPIO_BSRR_BS13 |
				GPIO_BSRR_BS14 | GPIO_BSRR_BS5 | GPIO_BSRR_BS6;	//ABCDEFG
	}

	if (num == 9)
	{
		GPIOB->BSRR = GPIO_BSRR_BS0 | GPIO_BSRR_BS1 | GPIO_BSRR_BS2 |
				GPIO_BSRR_BS13 | GPIO_BSRR_BS5 | GPIO_BSRR_BS6;	//ABCDFG
	}

	if(indicator_index == 0)
			GPIOC->BSRR = GPIO_BSRR_BS0;
	if(indicator_index == 1)
			GPIOC->BSRR = GPIO_BSRR_BS1;
	if(indicator_index == 2)
			GPIOC->BSRR = GPIO_BSRR_BS2;
	if(indicator_index == 3)
			GPIOC->BSRR = GPIO_BSRR_BS3;

}

uint16_t read_adc(uint8_t channel)
{
	ADC1->SQR3 |= channel & (0b11111);
	ADC1->CR2 |= ADC_CR2_SWSTART;
	while((ADC1->SR & ADC_SR_EOC)==0);
	return ADC1->DR;
}

void convert(void)
{
	uint8_t length;
	uint32_t a;
	adc = read_adc(0);
	adc = adc - 56;
	a = adc * 375;
	for(uint8_t index = 0; index <= 3; index++)
	{
		length = a/409600;
		if (length == 0)
		{
			a *= 10;
			value[index] = length;
		}
		else
		{
			value[index] = length;
			a -= length*409600;
			a *= 10;
		}
	}
}


void indication(void)
{
	uint8_t num_i = 0;
	while (true)
	if((TIM2->SR & TIM_SR_UIF) != 0)
	{
			indicator(value[num_i], num_i);
			TIM2->SR &= ~TIM_SR_UIF;
			num_i++;
			if (num_i == 4)
				num_i = 0;
	}
}

int main(void)
{

	initClk();
	init_ports();
	init_tim2();
	init_tim3();
	init_adc();
	indication();
    /* Loop forever */
	for(;;);
}
